language: node_js
node_js:
- '6.11'
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX="g++-4.8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_deploy: "mkdir artifact; tar --exclude artifact --exclude \\.git -zcvf artifact/trafikanten-hjemme.tar.gz .; mv artifact/trafikanten-hjemme.tar.gz ."
deploy:
  provider: releases
  api_key:
    secure: PNg+ABrB2L+EbSVP9xhJwKkUR9V2WSCQY3+l7A4/pnnzIuP65jtQrtdHbijmRIz4b2uQFB3f8ubN7qRiQ26N8D2SVDxKRTsrhqeas8ZLPv1afHXeyYvZ693bCDhE7YP8DCQOJ8+YP8hOVwyUh7Kwu0RbuIxxH/+3RS4wAgXXrR4=
  file: trafikanten-hjemme.tar.gz
  skip_cleanup: true
  on:
    repo: vramdal/trafikanten-hjemme
    all_branches: true
    tags: true

